apiVersion: v1
kind: Pod
metadata:
  name: kre-dashboard
  labels:
    app: kre-dashboard
spec:
  containers:
    - name: nginx
      image: nginx:20220420
      ports:
        - containerPort: 80
      volumeMounts:
      - mountPath: /home/app/web/staticfiles/
        name: staticassetvol
    - name: app
      image: app:app-20220420
      command: ["gunicorn"]
      args: ["kre_dashboard.wsgi:application", "--bind", "0.0.0.0:8000", "--workers" , "9", "--timeout", "300"]
      ports:
      - containerPort: 8000
      volumeMounts:
      - mountPath: /home/app/web/staticfiles/
        name: staticassetvol
  volumes:
      - name: staticassetvol
        emptyDir: {}