apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
  labels:
    app: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
          ports:
            - containerPort: 9200
          env:
          - name: xpack.security.enabled
            value: "false"
          - name:  discovery.type
            value: "single-node"
          - name:  use_ssl
            value: "false"

